on: push

jobs:

build:
  runs-on: 'ubuntu-latest’
  steps:
   - uses: actions/checkout@v4
   - name: 'Set up JDK 1.17’
     uses: actions/setup-java@v4
     with:
      distribution: 'temurin’
      java-version: '17
   - name: ‘Generate build number’
     id: buildnumber
     uses: onyxmueller/build-tag-number@v1
     with:
      token: ${{ secrets.GITHUB_TOKEN }}
   - name: Build internal
     uses: gradle/gradle-build-action@v3
     env:
      ORG_GRADLE_PROJECT_version_code: ${{ steps.buildnumber.outputs.build_number }}
     with:
      arguments: build
